version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: medici_users_mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: medici
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: