version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: medici_users_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: medici
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - medici_network

  # Redis Service
  redis:
    image: redis:latest
    container_name: medici_users_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - medici_network

  # Spring Boot Application Service
  medici_app:
    image: openjdk:17-jdk-slim  # Use OpenJDK for Java 17
    container_name: medici_user_hub_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:medici@mongodb:27017/medic_user_db?maxPoolSize=1000&minPoolSize=50
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_ACCESS_TOKEN_EXPIRATION_MS: 900000
      JWT_REFRESH_TOKEN_EXPIRATION_MS: 86400000
    depends_on:
      - mongodb
      - redis
    networks:
      - medici_network

volumes:
  mongodb_data:
  redis_data:

networks:
  medici_network:
